# Generated by Django 3.1.5 on 2021-01-09 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blast_cell', models.FloatField(verbose_name='Количество бластных клеток')),
                ('blast_cell_deviation', models.FloatField(verbose_name='Количество бластных клеток')),
                ('promyelocytes', models.FloatField(verbose_name='Количество милеоцитов')),
                ('promyelocytes_deviation', models.FloatField(verbose_name='Количество милеоцитов')),
                ('neutrophils_myelocytes', models.FloatField(verbose_name='Количество нейтрофилов')),
                ('neutrophils_myelocytes_devition', models.FloatField(verbose_name='Количество нейтрофилов')),
                ('neutrphils_metamyelocytes', models.FloatField(verbose_name='Нейтрофилы: Миелоциты')),
                ('neutrphils_metamyelocytes_devition', models.FloatField(verbose_name='Количество нейтрофилов')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
    ]
