# Generated by Django 3.1.3 on 2021-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='blast_cell',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество бластных клеток'),
        ),
        migrations.AlterField(
            model_name='result',
            name='neutrophils_myelocytes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество нейтрофилов'),
        ),
        migrations.AlterField(
            model_name='result',
            name='neutrphils_metamyelocytes',
            field=models.PositiveIntegerField(default=0, verbose_name='Нейтрофилы: Миелоциты'),
        ),
        migrations.AlterField(
            model_name='result',
            name='promyelocytes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество милеоцитов'),
        ),
    ]
