# Generated by Django 3.1.5 on 2021-01-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210108_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient', default=None),
        ),
    ]
